id: A26532F25
title: Toh_308-Questions_Regarding_Death_and_Transmigration-v2
type: translation
pechas:
- I29D4E954
- IDBA5DA1F
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-072-008
  eft-text-version: 1.22.3 2020
  title: Toh_308-Questions_Regarding_Death_and_Transmigration-v2
alignment_to_base:
  I29D4E954/7B93: '5996'
  IDBA5DA1F/CD59: '5996'
